Prevent DOMException if data storage is disabled
boffinHouse/rawblock pull request #23
Opened 2016-11-01 10:08 UTC by snackfurt

At least Chrome throws an Exception when trying to access window.XXXstorage and user has disabled data storage:
> Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

This happens as soon as you try to access the storage, so additional try-catch is needed.

![bildschirmfoto vom 2016-10-31 14-15-43](https://cloud.githubusercontent.com/assets/19982047/19886420/759147ce-a023-11e6-8955-b4e31c506ff2.png)

2016-11-01 10:27 UTC, aFarkas requested changes
Thanks bro. Just some small formal correction:

2016-11-01 10:27 UTC, aFarkas commented on sources/js/utils/rb_storage.js
> +        var storage = undefined;
all var should be at the start of the function. You don't need to declare a variable by explicitly assigning undefined.

Should look something like this:

```
        var storage;
        var testStr = rb.getID();

        try{
            storage = window[type + 'Storage'];
        } catch(e) {
            storage = {};
        }
```

2016-11-01 10:33 UTC, snackfurt commented
Sounds reasonable, done so.

2016-11-01 10:40 UTC, aFarkas approved these changes

2016-11-01 10:40 UTC, merged

2016-11-01 21:30 UTC, DracoBlue commented
👍

2016-11-02 08:55 UTC, aFarkas commented
I published a new version with just your fix in it: 0.7.9